services:
  - type: web
    name: image-recipe-generator-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd app/api && gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: image-recipe-generator-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd app/frontend && streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: BACKEND_URL
        value: https://image-recipe-generator-api.onrender.com
    autoDeploy: true
