services:
  - type: web
    name: image-recipe-generator-api
    env: python
    buildCommand: |
      mkdir -p /opt/render/project/src
      cp -r . /opt/render/project/src
      cd /opt/render/project/src
      pip install -r requirements.txt
    startCommand: cd app/api && gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
